### ISSUE TITLE
[Feature] Add LifecycleAwareFirebaseMessagingService

### ISSUE THREAD

**Issue by l2hyunwoo** [skydoves/firebase-android-ktx#2]
**Is your feature request related to a problem?**

Currently, FirebaseMessagingService is not lifecycle-aware, so if you are handling certain asynchronous tasks under the hood, you have to manually terminate those jobs onDestroy. Having a utility feature like lifecycleScope in LifecycleService would make this task very easy to handle, so I propose to implement and add such a feature.

**Describe the solution you'd like:**

Implement LifecycleAwareFirebaseMessagingService -> Also I want to take this task

**Describe alternatives you've considered:**

**Comment by skydoves** [comment]
Hey @l2hyunwoo, thank you so much for suggesting this fantastic feature! I’d love to review your implementation once you’ve completed the task. Here are my suggestions for the module and class names:

- `firebase-messaging-lifecycle-ktx`
- LifecycleFirebaseMessagingService

I'm looking forward to reviewing your implementation!
